config/routes.rb
Rails.application.routes.draw do
  
  get '/login', to: 'sessions#new'

  #post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  post 'cerlogoff', to: 'sessions#cerlogoff'

  post 'cerlogin', to: 'sessions#cerlogin'

  post 'post_create', to: 'posts#create'

  get '/signup',to: 'users#new'

  post 'content_create', to: 'contents#create'

  root 'static_pages#home'




  resources :users

  resources :posts,          only: [:create, :destroy, :show]

  resources :content

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
	belongs_to :post
	belongs_to :user
	default_scope -> { order(created_at: :asc) }
	validates :ct, presence: true, length: { maximum: 1000 }
	validates :user_id, presence: true

	
	
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :contents, dependent: :destroy
	belongs_to :user
	validates :subject, presence: true, length: { maximum: 50}
	validates :user_id, presence: true
	default_scope -> { order(updated_at: :desc) }

end

app/models/session_id.rb
class SessionId < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email.downcase! }
	validates :name, presence: true
	em_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
	                                  format: { with: em_regex },
	                                  uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
	has_many :posts, dependent: :destroy
	has_many :contents, dependent: :destroy


	def self.new_token
	end

	def feed
		Post.where()
	end

	def self.digest(token)
		BCrypt::Password.create(token)
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_login, :is_login?
  protect_from_forgery with: :exception
  helper_method :logged_in?
  helper_method :current_user

  def current_user?(user)
    @current_user = current_user
    @current_user == user
  end

  def current_post
    Post.find(params[:post_id]) if Post.all.ids.include?(params[:post_id].to_i)
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id].present? && User.all.ids.include?(session[:user_id])
  end
  
  def logged_in?
    session[:user_id].present?
  end
  
  def log_in(user)
  	session[:user_id] = user.id
  end

  def authenticated?()
  end
  
  def store_location
     session[:forwarding_url] = "http://tnforum.tiny.com" + (request.original_url).split("?")[0].split("http://127.0.0.1:3001")[1] if request.get?
  end

  def authen_url?(url)
    if BCrypt::Password.new(url[:f]) == "9fj90k.'f9f9$imjlnfdiso9/%#,f&#{(url[:time].to_i-95536).to_s}#{url[:user]}"
      user = User.find_by(email: url[:user])
      log_in user
      redirect_to user
    else
      redirect_to "http://sso.tiny.com/login?url=http://tnforum.tiny.com/login/"
    end
  end

  def update_login
    session[:user_id] = nil   if current_user && current_user.online == false  
  end

  def is_login?
    if !logged_in? 
      if  params[:unlogin] == nil
        redirect_to "http://sso.tiny.com/login?url=#{store_location}&login=1"
      # else
      #  if params[:session_id].present?
      #     session[:id] = params[:session_id]
      #     s_id = SessionId.find_by(s_id: session[:id])
      #     if params[:unlogin] == "2" && s_id.online == true
      #       redirect_to "http://localhost:3000/login?url=#{store_location.split("?")[0]}&login=1"
      #     #debugger
      #     end
      #   end
      end        
    end
  end

  

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

	def create
		@content = current_post.contents.build(ct: params[:content][:ct])
		@content.user_id = current_user.id
		if  @content.valid?
			@content.post.content_count += 1
			@content.post.save
			@content.floor = @content.post.content_count
			@content.save
			flash[:success] = "回复成功"
			redirect_to current_post
		else
			flash[:success] = "回复失败，请检查内容是否为空或长度过长"
			redirect_to current_post
		end
	end
end




	

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def show
		@post = Post.find(params[:id])
		@contents = @post.contents.paginate(page: params[:page])
	end

	def create
		@post = current_user.posts.build(subject: params[:post][:subject])
		@first_content = @post.contents.build(ct: params[:post][:ct])
		@first_content.user_id = current_user.id
		if @first_content.valid?
				@first_content.floor = @post.content_count = 1
				@post.save
				@first_content.save
				flash[:success] = "新建帖子成功。"
				redirect_to @post 

		else
				redirect_to root_url
				flash[:danger] = "新建帖子失败，请检查内容是否为空，或长度过长。"
		end
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if params[:f] == nil
      redirect_to "http://sso.tiny.com/login?url=#{store_location}"
    else
      authen_url?(params)
    end
  end

  # def create
  # 	if @user = User.find_by(email: params[:session][:email].downcase)
  # 		if BCrypt::Password.new(@user.password_digest) == params[:session][:password]
  # 			redirect_to @user
  # 			flash[:success] = "登录成功"	
  # 			log_in @user
        
  # 		else
  # 			flash[:danger] = "密码错误"
  # 			render 'new'
  			
  # 		end
  	
  # 	else
  # 	 	flash[:danger] = "无效的邮箱"
  # 	 	render 'new'
  		
  # 	end
  # end

  def destroy
    user = current_user
    user.online = false if user.present?
    user.save
    # if s_id = SessionId.find_by(s_id: session[:id])
    #   s_id.online = false
    #   s_id.save
    # end
  	session[:user_id] = nil

    redirect_to root_url
  end



  def cerlogoff
    if BCrypt::Password.new(params[:cer].split("!@#$%")[0]) == "9fj90k.'f9f9$imjlnfdiso9/%#,f&#{(params[:cer].split("!@#$%")[-1].to_i-95536).to_s}"
      session[:user_id] = nil
      redirect_to params[:url]
    else
      redirect_to root_url
    end
    
  end

  def cerlogin
    if BCrypt::Password.new(params[:cer].split("!@#$%")[0]) == "9fj90k.'f9f9$imjlnfdiso9/%#,f&#{(params[:cer].split("!@#$%")[-2].to_i-95536).to_s}#{params[:cer].split("!@#$%")[-1]}"
      user = User.find_by(email: params[:user])
      session[:user_id] =  user.id 
      redirect_to params[:url]
    else
      redirect_to root_url
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@posts = Post.all.paginate(page: params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def show
    if User.all.ids.include?(params[:id].to_i)
      @user = User.find(params[:id])
      @posts = @user.posts.paginate(page: params[:page])
    else
      redirect_to root_url
      flash[:danger] = "could not find the user."
    end
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params) 
  	if @user.save 
      log_in @user
  		render 'show'
  	else

  		render 'new'
      flash[:danger] = "error messages."
  	end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "修改成功"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end

    def set_user
      @user = User.find(params[:id]) if User.all.ids.include?(params[:id].to_i)
    end

    def correct_user
      set_user
      redirect_to root_url unless current_user? @user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/_content.html.erb
<li id="content-<%= content.id %>">
  
  <span class="content"><%= "#{content.ct}"%></span>
  <span class="timestamp">
    回复于 <%= "#{Time.at content.created_at.to_i}".split("+")[0] %>
    &nbsp<%= "#{content.floor}楼"%>&nbsp &nbsp 
    <div style="color: black;display: inline-block;" >
    --<%= content.user.name %>
    </div>
  </span>
</li>

app/views/layouts/_dropdown.html.erb
<li><%= link_to "Users", "#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", "#" %></li>
              <li><%= link_to "Settings", "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", "#", method: "delete" %>
              </li>
            </ul>
          </li>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Tiny 论坛", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right color">
        <li><%= link_to "首页", root_path %></li>
        <li><%= link_to "帮助", "#" %></li>
        <% if logged_in? %>
        <li><%= link_to "我的账户", current_user  %></li>
        <li><%= link_to "退出", logout_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "登录", login_path %></li>
        <% end %>
        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type,message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <span class="content"><%= link_to  post, id: "subject" do%>
  主题：<%= "#{post.subject}" %>  &nbsp &nbsp &nbsp      楼主：<%= "#{post.user.name }" %> <% end %></span>

  
  <span class="content"><%= link_to "#{post.contents.first.ct}",post %></span>
  <span class="timestamp">
    在<%= "#{Time.at post.updated_at.to_i}".split("+")[0] %>时回复  
    <div style="color: black; display: inline-block;">
    已有<%= "#{post.content_count}" %>条回复
    </div>
  </span>
</li>

app/views/posts/show.html.erb
<%= provide(:title, @post.subject) %>
<div class="row">
<div class="col-md-4 col-md-offset-4">
         
       <h3> <%= "主题:  #{@post.subject}" %></h3>
     
</div>
</div>
<% if @post.contents.any? %>
      <h3>已回复： <%= @post.content_count %></h3>
      <ol class="microposts">
       <% @contents.each do |content| %>
       <%= render content %>
       <% end %>
      </ol>
      <%= will_paginate @contents %>
    <% end %>
   

<%= form_for(:content, url: content_create_path) do |f| %>
<div class='col-md-6'>
<%= f.text_area :ct, class: "form-control", style: "height: 120px;" %>
</div>
<div class="col-md-12"></div>
<div class='col-md-4'>
<%= f.submit "回复", class: "btn btn-primary" %>
</div>
<%= hidden_field_tag :post_id, @post.id %>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title,"Home") %>
<div class="row">
<div class="signup">
<%= link_to "Signup", signup_url %>
</div>
<div class="col-md-8">
    <% if @posts.any? %>
      <h3> </h3>
      <ol class="microposts">
       <% @posts.each do |post| %>
       <%= render post %>
       <% end %>
      </ol>
      <%= will_paginate @posts %>
    <% end %>
  </div>
<hr>
<div class="col-md-8">
<% if logged_in? %>

<%= form_for(:post, url: post_create_path) do |f|%>

<%= f.label "主题" %>
<%= f.text_field :subject, class: "form-control" %>

<%= f.label "内容" %>
<%= f.text_area :ct, class: "form-control ", style: "height: 120px;" %>

<div class="col-md-4 col-md-offset-4">
<%= f.submit "新建", class: "btn btn-primary" %>
</div>
<% end %>
</div>



<% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, current_user.name) %>
<h1>资料编辑</h1>
<div class="row">
<div class="col-md-4 col-md-offset-4">
<%= form_for @user do |f| %>

<%= f.label "用户名" %>
<%= f.text_field :name, class: "form-control" %>

<%= f.label "邮箱" %>
<%= f.email_field :email, class: "form-control" %>

<%= f.label "密码" %>
<%= f.password_field :password, class: "form-control" %>

<%= f.label "确认密码" %>
<%= f.password_field :password_confirmation, class: "form-control" %>

<%= f.submit "修改" , class: "btn btn-primary" %>
<% end %>

</div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Signup")%>
<h1>注册</h1>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
	<%= form_for(@user) do |f| %>

	<%= f.label "用户名:"  %>
	<%= f.text_field :name, class: "form-control" %>

	<%= f.label "邮箱:" %>
	<%= f.email_field :email, class: "form-control" %>

	<%= f.label "密码:" %>
	<%= f.password_field :password, class: "form-control" %>

	<%= f.label "密码确认:" %>
	<%= f.password_field :password_confirmation, class: "form-control" %>

	<%= f.submit "提交",class: "btn btn-primary" %>
	<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title,"用户") %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
    <div >
		<%= link_to "修改资料", edit_user_path(@user) %>
	</div>
      <h1>        
        <%= "name:  #{@user.name}" %>
      </h1>
      <h1>        
        <%= "email:  #{@user.email}" %>
      </h1>
    </section>
  </aside>

  <div class="col-md-8">
  <h3>我的帖子数： <%= @user.posts.count %></h3>
    <% if @user.posts.any? %>
      
      <ol class="microposts">
       <% @posts.each do |post| %>
       <%= render post %>
       <% end %>
      </ol>
      <%= will_paginate @posts %>
    <% end %>
  </div>
  </div>